### ISSUE TITLE
[Bug]: Error: Port: 7860 is not open yet. Please wait, this may take upwards of 60 seconds...

### ISSUE THREAD

**Issue by wewlad-dev** [sd-webui/stable-diffusion-webui#1144]
### What happened?

Can't open the port on localhost

![Screenshot_6666](https://user-images.githubusercontent.com/59626410/190320957-87b7bebe-0844-4057-9bfb-fb4d0a77d93a.png)

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Error: Port: 7860 is not open yet. Please wait, this may take upwards of 60 seconds...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Da1daidaidai** [comment]
this issue also happened in linux. It works at the fisrt time. When I refresh the page and try to strat it again, the same bug appeares.

**Comment by wewlad-dev** [comment]
Tried all means of resolution and none worked
- Allow firewall rule for that TCP port -> failed
- disable firewall completely on windows -> failed
- Disable router firewall -> failed
- Changed router with another one, disabled firewall too -> failed
- Run with/without admin privilege -> failed
- Disconnect network access completely -> failed

I have no idea what to do/try anymore.

**Comment by the-emmons** [comment]
@wewlad-dev
I don't know why this is happening, since the port doesn't appear to be listening. With that said, you can fix it by manually changing the server name and port in `./scripts/webui.py`, as shown here:
![image](https://user-images.githubusercontent.com/70683790/192075964-5d333497-6f53-4698-95e8-0215ff61695a.png)
