### ISSUE TITLE
[BUG] [JS] SD class abstraction bugs

### ISSUE THREAD

**Issue by nderscore** [sd-webui/stable-diffusion-webui#343]
## Asynchronous code and arguments

The current implementation of the `SD` class from #297 does some odd things to pass the arguments around:

```py
# Wrap the typical SD method call into async closure for ease of use
# If you call frontend method without wrapping
# DONT FORGET to bind input argument if you need it: SD.with(x)
def w(sd_method_call):
    return f"async (x) => {{ return await SD.with(x).{sd_method_call} ?? x ?? []; }}"
```

This `with()` method stores the arguments of the most recently called function in a local property `x`:

```js
with (x) {
  this.x = x;
  return this;
}
```

And then that `x` is referenced elsewhere in the methods themselves.

Because these method functions can be asynchronous, it is possible for multiple of them to be happening simultaneously.

Because all the functions share the same instance of the `SD` class, it's possible for `this.x` to be overwritten by other methods being called while another function is still running.

This is currently unlikely to occur (or at least I haven't found a case to reproduce it yet), but the likelihood will definitely increase over time as more features are added.

## Return value assumption

The wrapper code also includes this optional-chain: `?? x ?? []`. I think this is a bad assumption to make and it should trust the return value of the underlying function that it's calling instead. 

Right now, it's not possible for a function to explicitly return a `null` when non-null arguments were passed.

## Proposal

I think this should probably just pass the arguments as arguments to the underlying function instead. Maybe I'm missing some context as to why it was implemented this way, but I can't think of any good reason to not do it this way.

And the wrapper could accept an optional second argument for passing extra non-gradio arguments to the function if they're needed:

```py
# wrapper code for calling javascript code from the SD class
def wrap_js_method(sd_method_name, optional_arguments="undefined"):
    return f"async (gradioArguments) => {{ return await SD.{sd_method_name}.(gradioArguments, {optional_arguments}); }}"
```

```py
wrap_js_method("foo_bar")
# maybe there's a better way to handle extra arguments than this that accepts a list :P
wrap_js_method("foo_bar", '"arg2", "arg3"')
```

Open to other ideas for how to solve it though.

**Comment by codedealer** [comment]
Hey there @nderscore, I'm the author of the SD class. Thank you for paying close attention to the codebase!

## Regarding `x` ##
This is basically the Gradio way. You should keep in mind that `x` is not just another argument. Js functions at the bottom of `css_and_js.py` are preprocessors that take the input from the Gradio blocks (colloquially named `x`) and should pass it to a python function later. Now, that python function may not exist but as far as frontend concerned it does.

### Why `.with(x)`? ###
It is a convenience thing to keep the method signatures clean. Not every method requires input from Gradio and a developer might just forget about it. To keep that from happening the latest Gradio input is bound to the object itself.

That introduces a potential pitfall with the async methods, you are correct! However I judged it a tolerable risk:
> it's possible for this.x to be overwritten by other methods being called while another function is still running.

This is a fringe case the responsibility of handling of which in my opinion should rely on the shoulders of the developer who runs concurrent code. As a safeguard against it we can make `this.x` an immutable property so that every method can only operate with a copy and return said copy to Gradio.

If you can provide some plausible example where that directly compromises the integrity of SD class I'm interested in discussing it further.

Remember: **w() method is optional**. If you don't like it you can call your own method directly and pass `x` into it circumventing `.with()`. Then **it is up to you** to honor the Gradio contract of taking x in your method and returning it. `w()` method in python just ensures that this contract is respected in case a frontend developer forgets about it.

Which brings me to my next point:

### Return value assumption ###
> The wrapper code also includes this optional-chain ... I think this is a bad assumption to make and it should trust the return value of the underlying function that it's calling instead.

`w()` wrapper method was created exactly to remove this need to trust a frontend dev to honor Gradio contract  — treat it as a syntactic sugar. 

And this is not optional chaining but null coalescing and it always respects the return value (as long as it is not nullish). Like I mentioned before not all methods in SD class might need `x` similarly not all methods might return it (see `SD.clickFirstVisibleButton()` as an example of that).

>  it's not possible for a function to explicitly return a null

It is perfectly fine for _your method_ to return a `null` but it is not fine for a `_js` hook in python to pass null. The underlying Gradio code on the frontend expects the return value to be a primitive, an object or an iterable which is why as a fallback I used `x ?? []`. Testing showed this is the most reliable way I could find to handle return. An empty array is passed to python as an empty list which is equivalent to passing `None` (internally Gradio casts `None` to `[]` in input arguments anyway).

**Comment by codedealer** [comment]
I will keep this section separate in case @hlky wants to incorporate it into Contribution guide for frontend later.

## Implementing a new frontend method ##
_In a general sense a _js method is a preprocessor to a python event handler. It takes `x` as an input and returns some modified version of it. The following workflow is designed to abstract away this strict requirement and allow you to write any js logic you want._

1. In your Gradio component in `frontend/frontend.py` set up a `_js` hook that will call a helper method. Give it a clear name that explains what it does and pass it any arguments you need **besides input value `x`**. Do not worry about `x` you will get access to it anyway. For example your method might look like this 
```_js=js_move_image('img2img_gallery_output', 'img2img_editor')```
It telegraphs that your js function will move the image between a Gallery component (with id 'img2img_gallery_output') and Image (with id 'img2img_editor').
2. Implement your new helper in `frontend/css_and_js.py`. It should return a string that represents a correct js code. This is where you will call your future js function. Use `w()` wrapper defined here to create a string. `w()` can accept your method invocation as a string parameter. In the aforementioned example let's say the js function we create will be called `moveImageFromGallery`. So the python helper method's implementation in this case will look like this:
```
def js_move_image(from_id, to_id):
    return w(f"moveImageFromGallery('{from_id}', '{to_id}')")
```
We pass the arguments of python's `js_move_image` to js `moveImageFromGallery` seamlessly. Later when your component fires and event `_js` hook will call this method and pass your arguments along.
3. Implement your new js function as a method in SD class located in `frontend/js/index.js`. In addition to the arguments you passed from your helper function you have access to `this.x` which is the input variable passed from Gradio to `_js` (see https://gradio.app/custom_CSS_and_JS/#custom-js). Optionally any value you return from your method will be passed to python event handler defined in your component. The method above would look like this:
```
class SDClass {
    // ...
    moveImageFromGallery (fromId, toId) {
      // get first image's data from the gallery
     const imageData = this.x[0];

      // ...your code here

      // optionally return the imageData to be passed into your python event handler
      return imageData
    }
```

And that's it!

### Important Notes ###
* If your implementation is very large consider encapsulating it in a namespace. Add a property to SD class which will serve as your namespace (for example of that see Painterro implementation in `frontend/js/index.js`). Then from your python helper you can call it `w(f"MyNamespace.myMethod()")`.
* Internally `w()` wraps your method call in async closure so your methods can be `async`!
* **Advanced**: you don't have to use `w()` as long as the string you return in your python helper method is valid javascript.

**Comment by nderscore** [comment]
> This is a fringe case the responsibility of handling of which in my opinion should rely on the shoulders of the developer who runs concurrent code. As a safeguard against it we can make this.x an immutable property so that every method can only operate with a copy and return said copy to Gradio.

The user is in control of when each gradio method is executed, not the developer. These methods are executed as a side-effect of a user action, such as a button press. I promise you, it's going to the source a bug eventually.

> It is a convenience thing to keep the method signatures clean. 

This seems like a really bad justification to implement such a weird workaround, when you could just as easily pass arguments normally.

**Comment by codedealer** [comment]
@nderscore I acknowledge the possible risk of such implementation of `with`. Give me a bit of time I will remove the reliance on a `this.x` field. Better safe than sorry.

 > It doesn't allow a method to return a null if it wants to.

I think I got what you mean, it's an incorrect assumption to return `x`. It should be amended to this `methodResult ?? []`. If the method wants to output nullish value, let is basically. Still returning `null` itself is invalid.
The Gradio code for handling output expects an iterable.

**Comment by codedealer** [comment]
@nderscore I'd like your feedback on #381 please (can't tag you there for some reason)
