### ISSUE TITLE
[FEATURE REQUEST] Prompt Job Queue

### ISSUE THREAD

**Issue by mikenew02** [sd-webui/stable-diffusion-webui#408]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A system similar to Handbrake, where prompts go into a job queue that are executed in sequence.
This way I don't have to check every x minutes if the prompt is done or not to put in a new prompt.

**Comment by vinyvince** [comment]
Please yes, batch processing... List as imput

**Comment by DJPatron** [comment]
It should be very useful.
Maybe it is suitable to reserve one special separator for this (for example '~' or '||' or '***' you name it), so that if it is present in the prompt line, python will divide the prompt into parts and execute all parts in queqe order.

Example:
Prompt like this:  **"gorgeous girl || cat riding a bicycle || me paying bills, sad face"**

Will result in queue like this:
**gorgeous girl
cat riding a bicycle
me paying bills, sad face**

...or is it already possible to do it in any way using some existing prompt matrix features?

**Comment by mikenew02** [comment]
It's not just the prompt that would go into the queue. Every variable would be accounted for.

- prompt
- width
- height
- steps
- seed
- sampler
- iterations
