### ISSUE TITLE
[Feature Request] Display images as they are generated

### ISSUE THREAD

**Issue by KyuubiYoru** [sd-webui/stable-diffusion-webui#446]
Currently, images only show up after all of them are done. Instead, show each image immediately after it is generated.

**Comment by JamesIV4** [comment]
It would be really great to see the steps as they are generated too.

**Comment by KyuubiYoru** [comment]
And the ability to cancel the current batch.

**Comment by ZeroCool940711** [comment]
@JamesIV4 @KyuubiYoru It's not possible for now because of how Gradio works. I am working on a Streamlit version of the WebUI which already has the option to stop the current generation and will have the image updated as it's been generated as streamlit lets you update any part of the app while it's running be it text, images or anything else but it's taking me some time because the main WebUI is also been updated so I'm always behind and trying to catch up, at least I have implemented most of the stuff on the Text to Image tab and soon will start to work on the Image to Image tab, if you want to follow the progress check this discussion #265, I try to put there the progress I make every now and then, I actually just started yesterday with the UI as I was waiting for the main UI to be stable but as I saw it was actually speeding up and more commits were coming in I decided to start with my version and try to keep up with the other version that is on gradio. I'm currently waiting for info on where in the code the image is generated for each step inside an iteration and as soon as I find where that is my version will be able to update the image in real time, as of now it does update faster than the other version as I made it so when you have a big batch of images the UI updates after each image is generated and saved to disk but I haven't managed to make it so it is updated more frequently on each step during each iteration, that would be the best way to have the image displayed as you can see the progress in real time but I need to find out where the image is generated and my brain went short circuit after being all day looking at the code, xD

**Comment by inukai132** [comment]
This feature is being developed by Gradio right now, hopefully when it gets merged in we can make use of it

**Comment by JamesIV4** [comment]
@ZeroCool940711 that sounds like something I want to try, if I pull your branch, will it leave the other files as they were? Or do I need to create a new copy of the repo?
