### ISSUE TITLE
[Bug]: Error Loading LDSR after installation of model.ckpt

### ISSUE THREAD

**Issue by darkstorm2150** [sd-webui/stable-diffusion-webui#488]
### What happened?

I followed the advice from the discussion, Im unsure if its missing more information for it to be activated.

Error loading LDSR:
Traceback (most recent call last):
  File "scripts/webui.py", line 359, in try_loading_LDSR
    LDSR = load_LDSR() # TODO: Should try to load both models before giving up
  File "scripts/webui.py", line 286, in load_LDSR
    from LDSR import LDSR
ModuleNotFoundError: No module named 'LDSR'

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
Git clone https://github.com/devilismyfriend/latent-diffusion into your stable-diffusion-main/src/ folder
Rename latent-diffusion-main folder to latent-diffusion
If on windows: run download_models.bat to download the required model files
Otherwise to manually install the model download [project.yaml](https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1) and [last.cpkt](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1) and rename last.ckpt to model.ckpt
Place both under stable-diffusion-main/src/latent-diffusion/experiments/pretrained_models/
Make sure you have both project.yaml and model.ckpt in that folder and path.
LDSR should be wokring now.

**Comment by darkstorm2150** [comment]
Made the mistake of git cloning https://github.com/CompVis/latent-diffusion instead of yours, it seems to be working now, thx!

**Comment by AbdBarho** [comment]
@devilismyfriend I am also facing a similar problem but while loading the config:

```
Loaded LDSR
Traceback (most recent call last):
  File "scripts/webui.py", line 1743, in imgproc
    image = processLDSR(image)
  File "scripts/webui.py", line 1679, in processLDSR
    result = LDSR.superResolution(image)
  File "/stable-diffusion/src/latent-diffusion/LDSR.py", line 315, in superResolution
    model = self.load_model_from_config()
  File "/stable-diffusion/src/latent-diffusion/LDSR.py", line 76, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
TypeError: __init__() missing 1 required positional argument: 'personalization_config'
```

The files are at the correct place:
```
(base) root@6bf18db60a15:/# cd /stable-diffusion/src/latent-diffusion/experiments/pretrained_models/
model.ckpt    project.yaml
```

I think there are two possible explainations:
1. the configuration file I have is the wrong one, because it does not have `personalization_config`
2. the LDSR is wrongly trying to import `/stable-diffusion/ldm/util.py` instead of `/stable-diffusion/src/latent-diffusion/ldm/util.py`

**Comment by AdamNizol** [comment]
If you are using windows then the bat file that they say works may not. It didn't for me since the curl command requires some ssl certification or something so the bat was throwing errors but closed on its own afterwards so you couldnt tell it went wrong without checking the folder and seeing that no files were downloaded. I added a pause to the end of the bat file which let me see the error and fix it. It was an easy fix in the end by adding the --ssl-no-revoke flag to both curl commands in the bat file.

**Comment by Renaldas111** [comment]
Where is download_models.bat file? If it is download_models.sh, how to run it on Windows?

**Comment by bbecausereasonss** [comment]
Get this error with the .bat in windows

Press any key to continue . . .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

**Comment by bbecausereasonss** [comment]
Exception: LDSR model not found at path ./src/latent-diffusion\experiments/pretrained_models\project.yaml

**Comment by Hafiidz** [comment]
Maybe try the manual option? hopefully we didnt give it death hug, hahaha.

**Comment by Yash503** [comment]
installed everything correctly, but in the last step, installing pip dependencies keeps loading and never stops.

**Comment by devilismyfriend** [comment]
I'm sorry but I'm currently away from my country and wasn't aware of the
latest repo merge so afaik LDSR is completely broken

**Comment by Hafiidz** [comment]
Just in case others come to this issue page later, latest instruction for LDSR is [here](https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation#ldsr) and more [details here](https://github.com/Hafiidz/latent-diffusion#fork-for-use-with-sd-webui)

**Comment by naavis** [comment]
I'm having this same issue with the `master` version of `sd-webui`. I'm running on Windows, and running the web UI using Docker Compose. The relevant `model.ckpt` and `project.yaml` files are in the correct place, the model validation at the beginning of starting the container.

You can see the output here:

```bash
sd  | Validating model files...
sd  | checking model.ckpt...
sd  | model.ckpt is valid!
sd  |
sd  | checking GFPGANv1.3.pth...
sd  | GFPGANv1.3.pth is valid!
sd  |
sd  | checking RealESRGAN_x4plus.pth...
sd  | RealESRGAN_x4plus.pth is valid!
sd  |
sd  | checking RealESRGAN_x4plus_anime_6B.pth...
sd  | RealESRGAN_x4plus_anime_6B.pth is valid!
sd  |
sd  | entrypoint.sh: Launching...
sd  | Found GFPGAN
sd  | Found RealESRGAN
sd  | Found LDSR
```

Yet when I go to the web UI and try to upscale an image with LDSR in the Image Lab tab, it fails with the following error:
```
sd  | Processing images...
sd  | Unloaded Stable Diffusion
sd  | Unloaded GFPGAN
sd  | Traceback (most recent call last):
sd  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd  |     output = await app.blocks.process_api(
sd  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
sd  |     predictions, duration = await self.call_function(fn_index, processed_input)
sd  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
sd  |     prediction = await anyio.to_thread.run_sync(
sd  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
sd  |     return await get_asynclib().run_sync_in_worker_thread(
sd  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd  |     return await future
sd  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd  |     result = context.run(func, *args)
sd  |   File "scripts/webui.py", line 1850, in imgproc
sd  |     ModelLoader(['LDSR'],True,False) # Load used models
sd  |   File "scripts/webui.py", line 1946, in ModelLoader
sd  |     global_vars[m] = load_LDSR()
sd  |   File "scripts/webui.py", line 306, in load_LDSR
sd  |     from LDSR import LDSR
sd  | ModuleNotFoundError: No module named 'LDSR'
```

**Comment by naavis** [comment]
Nevermind, it was easier to test than I anticipated. It started working after cloning the whole repository into the folder as described!

**Comment by victorchall** [comment]
> Git clone https://github.com/devilismyfriend/latent-diffusion into your stable-diffusion-main/src/ folder Rename latent-diffusion-main folder to latent-diffusion If on windows: run download_models.bat to download the required model files Otherwise to manually install the model download [project.yaml](https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1) and [last.cpkt](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1) and rename last.ckpt to model.ckpt Place both under stable-diffusion-main/src/latent-diffusion/experiments/pretrained_models/ Make sure you have both project.yaml and model.ckpt in that folder and path. LDSR should be wokring now.

This fixed my issue, probably need to specify this repo in instructions as most are going to use the compvis/latent-diffusion

**Comment by Hafiidz** [comment]
@victorchall & @naavis 

Hi, I am curious on your flow of installation, since I am doing most of the updates recently for the installation guide in the wiki. We have included the latest steps [here](https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation#ldsr). If you don't mind me asking, was that link unclear or is there a guide somewhere else that wasn't updated or unclear. Wanted to help others coming in later, so need to know where we need to improve. Appreciate the help to clarify.

**Comment by victorchall** [comment]
The readme.md only states
`LDSR
Download LDSR [project.yaml](https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1) and [model last.cpkt](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1). Rename last.ckpt to model.ckpt and place both under stable-diffusion-webui/src/latent-diffusion/experiments/pretrained_models/`

This should probably be changed to point to the wiki and not state anything at all rather than be incomplete.

**Comment by Hafiidz** [comment]
I see, I think I found the problem. The changes made to the readme was still in `dev` branch and not to the `master` yet.

![image](https://user-images.githubusercontent.com/3688500/189512261-78add1f9-8f1c-4bdc-853f-0b6718b006dd.png)

Really appreciate your kind feedback. Will check with team if they can migrate this updated message to the `master` branch sooner.

p/s, just noticed instrunctios typo, LOL

**Comment by juliosmacedo** [comment]
webui.cmd is stuck in a relaunch loop, seems to be because the app can't find any NVIDIA drivers. I use AMD cards, so nvidia drivers wouldn't be found anyway. Does this only  works on NVIDIA cards? 

Pasting here the 9th relaunch log:

Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "scripts/webui.py", line 453, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 444, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 159, in load_model_from_config
    model.cuda()
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 127, in cuda
    return super().cuda(device=device)
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 601, in _apply
    param_applied = fn(param)
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Adm\.conda\envs\ldm\lib\site-packages\torch\cuda\__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 9
Relauncher: Launching...
Error loading GFPGAN:
Traceback (most recent call last):
  File "scripts/webui.py", line 356, in <module>
    GFPGAN = load_GFPGAN(checking=True)
  File "scripts/webui.py", line 313, in load_GFPGAN
    raise Exception("GFPGAN model not found at path "+model_path)
Exception: GFPGAN model not found at path ./src/gfpgan\experiments/pretrained_models\GFPGANv1.3.pth

**Comment by satvikpendem** [comment]
My terminal says it found LDSR but the UI doesn't seem to detect it.

```
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
C:\Users\Satvik\anaconda3\envs\ldm\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
Iteration: 1/10
[MemMon] Recording max memory usage...
```

![image](https://user-images.githubusercontent.com/42670561/190011452-d678554b-4cde-4fca-a148-036692509572.png)

**Comment by Rustmongrel** [comment]
> ### Outdated, see edit below
> 
> @devilismyfriend I am also facing a similar problem but while loading the config:
> 
> ```
> Loaded LDSR
> Traceback (most recent call last):
>   File "scripts/webui.py", line 1743, in imgproc
>     image = processLDSR(image)
>   File "scripts/webui.py", line 1679, in processLDSR
>     result = LDSR.superResolution(image)
>   File "/stable-diffusion/src/latent-diffusion/LDSR.py", line 315, in superResolution
>     model = self.load_model_from_config()
>   File "/stable-diffusion/src/latent-diffusion/LDSR.py", line 76, in load_model_from_config
>     model = instantiate_from_config(config.model)
>   File "/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
> TypeError: __init__() missing 1 required positional argument: 'personalization_config'
> ```
> 
> The files are at the correct place:
> 
> ```
> (base) root@6bf18db60a15:/# cd /stable-diffusion/src/latent-diffusion/experiments/pretrained_models/
> model.ckpt    project.yaml
> ```
> 
> I think there are two possible explainations:
> 
>     1. the configuration file I have is the wrong one, because it does not have `personalization_config`
> 
>     2. the LDSR is wrongly trying to import `/stable-diffusion/ldm/util.py` instead of `/stable-diffusion/src/latent-diffusion/ldm/util.py`
> 
> 
> #### Edit
> 
> It turns out, this was a conflict with the models of [Textual Inversion](https://github.com/hlky/sd-enable-textual-inversion), which caused import confusion.

How did you fix this? I am having the same issue and have tried everything I can think of, which isn't much. Any help would be appreciated!

**Comment by Hafiidz** [comment]
@Rustmongrel, could you please confirm are you in `master` or `dev` channel ya? If in master, follow the installation steps as close as possible. Please ensure `.src` folder is not there before you first run `webui.cmd`

**Comment by Rustmongrel** [comment]
> @Rustmongrel, could you please confirm are you in `master` or `dev` channel ya? If in master, follow the installation steps [here](https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation) as close as possible. Please ensure `.src` folder is not there before you first run `webui.cmd`

Sorry, I have no idea what master or dev channel is so any guidance would be appreciated. I followed that guide to a T and everything but LDSR runs perfectly. When I try to use it I get that exact same error and I am here asking for help as it is the only place it is mentioned on the entirety of the internet. I have verified that everything is exactly where it is supposed to be so I am lost as to what it could be. I would really appreciate any help.

**Comment by Hafiidz** [comment]
@Rustmongrel, this is quite an edge cases then. Hard to troubleshoot here, I can suggest two things,

First, could you please try running `webui_streamlit.cmd` instead of `webui.cmd`, just in case.

Second, if the above doesn't help, I would suggest you to share this issue in our discord, somebody more knowledgeable might be able to help. You can see the link to discord on the github home/readme.

**Comment by Hafiidz** [comment]
`master` and `dev` is branch of git, since you are not doing anything else, you're on the `master` branch.

**Comment by devilismyfriend** [comment]
It's a bat file, which repo are you looking at

**Comment by Nirvan93** [comment]
I had the same error "ModuleNotFoundError: No module named 'LDSR'" constantly no matter what.
What helped me was going back on master branch to "The Merge (#1444)" commint and it's fixed.

I am confused about right directory of the ldsr files.
In one part in the docs you say to put model.cpkt and project.yaml under
' stable-diffusion-main/src/latent-diffusion/experiments/pretrained_models/' and in other doc you say to put it under 'stable-diffusion-webui/models/ldsr/' so where should it be?

PS. I also needed to change webui.py line 389 for GFPGANv1.3 to v1.4 since now link is downloading v.1.4

**Comment by ovasdi** [comment]
> I had the same error "ModuleNotFoundError: No module named 'LDSR'" constantly no matter what. What helped me was going back on master branch to "The Merge (#1444)" commint and it's fixed.
> 
> I am confused about right directory of the ldsr files. In one part in the docs you say to put model.cpkt and project.yaml under ' stable-diffusion-main/src/latent-diffusion/experiments/pretrained_models/' and in other doc you say to put it under 'stable-diffusion-webui/models/ldsr/' so where should it be?
> 
> PS. I also needed to change webui.py line 389 for GFPGANv1.3 to v1.4 since now link is downloading v.1.4

@Nirvan93 thanks for the workaround. [It works](https://github.com/sd-webui/stable-diffusion-webui/issues/1497#issuecomment-1283365292).
