### ISSUE TITLE
[Bug]: "Fix faces using GFPGAN" with txt2img - prevents random seed from being used. Uses previous seed if available, no output if no previous seed.

### ISSUE THREAD

**Issue by czamp** [sd-webui/stable-diffusion-webui#500]
### What happened?

Browser: Brave 1.43.88
OS: Windows 10 Home 10.0.19044
CPU: Intel Core i9-10900KF CPU @ 3.70 GHz
GPU: Dell / Alienware RTX 3080

Two manifestations I've noticed of what seems to be the same (or two closely related) bug(s):

1: When instantiating a new client session in txt2img, checking "Fix faces using GFPGAN" and attempting to generate an image results in no image being generated. This is the same for single image and batches.

2: When using an existing client session in txt2img, checking "Fix faces using GFPGAN" and attempting to generate an image results in the previous image or batch of images being generated, with GFPGAN face correction being applied.

In both cases, continual attempts to generate an image (or batch of images) produced the same results.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
No custom settings. Completely default.
```

### Relevant log output

```shell
Nothing unexpected. Looks as it should had an image been generated:

`
Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:05<00:00,  8.35it/s]
[MemMon] Stopped recording.
````
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GalaxyTimeMachine** [comment]
I don't think it's GFPGAN specific. I've had the same issue with the seed not being random, but only by selecting the options shown in the image here:

![image](https://user-images.githubusercontent.com/52193044/188138693-2a1e75f8-c4ba-456d-9ac7-629c0be2c52a.png)

**Comment by hlky** [comment]
>"Fix faces using GFPGAN" 

I don't know who added these options back in, they are supposed to only be on the Image Lab tab.

**Comment by GalaxyTimeMachine** [comment]
> > "Fix faces using GFPGAN"
> 
> I don't know who added these options back in, they are supposed to only be on the Image Lab tab.

The problem occurs even without selecting GFPGAN though.

**Comment by hlky** [comment]
@GalaxyTimeMachine That's not the point I was making, the code for gfpgan/esrgan on generation is an absolute mess because of how many different combinations of which images to output to file, to the grid and to the gallery people want, basically no one agrees and no one wants to use the options that accomplished most of the combinations to begin with.

I can confirm after enabling the gfpgan option on generation I am seeing a continuation of the previously used seed. I'll take a look but I'm still of the opinion that gfpgan and esrgan do not need to be applied to every image, you should be applying it after generation only on the images that actually need it.

**Comment by GalaxyTimeMachine** [comment]
@hlky Did you see my screenshot above? It had exactly the same problem with only the options in the picture selected. I could select "Generate" all day and get those identical pictures every time. No gfpgan and esrgan required. for that.

**Comment by GalaxyTimeMachine** [comment]
I was trying to reproduce it to show you more details, but I'm just hitting this bug now:

`  File "scripts/webui.py", line 1053, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 961, in process_images
    grid = image_grid(output_images, batch_size, force_n_rows=1 << ((len(prompt_matrix_parts)-1)//2))
  File "scripts/webui.py", line 458, in image_grid
    w, h = imgs[0].size
IndexError: list index out of range`

That requires that "Save individual images" is selected or you get that error, no output and no images in the UI.

**Comment by GalaxyTimeMachine** [comment]
Something has changed in the behaviour since I posted the screenshot. The problem I was having is now resoled, apart from having to select "Save individual images" to get any output at all. I confirm I only see the problem with GFPGAN or ESRGAN selected. Apologies for adding any confusion! I'm just trying to help :)
