### ISSUE TITLE
[Bug]: Infinite install pip dependencies

### ISSUE THREAD

**Issue by gamingoffice** [sd-webui/stable-diffusion-webui#829]
### What happened? 

[A bug happened!](https://user-images.githubusercontent.com/109173604/188978898-ea8ace43-2bef-4efc-80a4-39f3f661c4e1.png)   <--- press here for screen

I cant get past the Install pip dependencies i know sometimes it can takes long but my internet is realy fast and it still didnt finished over night (every step before that has been taken without problems)

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brutephishing** [comment]
i have the same error

**Comment by brutephishing** [comment]
i found the solution, you have to remove the src folder

**Comment by jaycaoln** [comment]
> i found the solution, you have to remove the src folder

why? i remove the src folder, it doesn't help。

**Comment by carlitoselmago** [comment]
confirmed, deleting src folder fixes the problem

**Comment by ShinghoiXu** [comment]
I have the same problem. I found that one core of my CPU is keeping running. It may be caused by the latest pip version. See a similar issue here: https://github.com/conda/conda/issues/10807#issuecomment-1122686016

**Comment by xaedes** [comment]
I also had the same problem.
The problem was that I put the model files in the src/gfpgan and src/realesrgan folders before starting the webui.cmd once.
The folders src/gfpgan and src/realesrgan MUST either contain the correct repo (as specified in environment.yaml) or they must not exist at all. Otherwise pip will run into infinite loop when trying to clone the repos.
You can put the models in the folders after pip is done.

**Comment by JoelPagliuca** [comment]
https://github.com/conda/conda/issues/10807#issuecomment-1227847972

this worked for me on my current Ubuntu setup
