### ISSUE TITLE
[FEATURE REQUEST]: Docker documentation

### ISSUE THREAD

**Issue by outlookhazy** [sd-webui/stable-diffusion-webui#904]
### What happened?

Migrate Docker documentation from old repo.  
Will need a minor change to indicate that .env_docker.example should be copied to .env_docker prior to attempting to run the compose build since docker-compose.yaml is hard-coded to look for the latter, which will be missing on a fresh clone. (see #720)

Related: might make sense to add Docker to the "Where are you running" part of the form

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by outlookhazy** [comment]
I'd do it myself, but can't clone the old wiki anymore and don't have permissions in any case

**Comment by sskorol** [comment]
FYI, I faced many issues while trying to run it in docker. And it's not only about missing env file.
There should be made a very important note that if one uses docker, they shouldn't manually download different stuff into `src` folder. Otherwise, the installation step fails on cloning key dependencies (as the folders already exist and are not empty). Moreover, you can notice this issue only during the first run as `CONDA_FORCE_UPDATE=false` by default.
Apart from that, there were different issues with missing modules, like cv2. Even after manual installation, it complained about missing `libgl1`. When all the deps' issues were resolved, webgui app failed to find a top-level frontend directory. I believe there's a PR for fixing that.

**Comment by outlookhazy** [comment]
I haven't rebuilt from scratch lately so I can't comment on that. My docker install works great - I wasn't thrilled with having to manage conda and pip on Windows. I'm also using a compose override file to assign a fixed IP and deploy it alongside a wireguard server so that I and some friends have remote access.

**Comment by oc013** [comment]
I wasn't able to transfer the discussion over because the old repo was archived unexpectedly.  

I recreated the documentation I wrote up before here and will try to keep it up to date: #922

**Comment by oc013** [comment]
@outlookhazy good to know you have this running all on a windows system. Would you comment on the discussion what version windows and gpu/drivers you had success with please?

**Comment by outlookhazy** [comment]
rebuilding from scratch to validate nothing has changed, will chime in on the discussion after

**Comment by outlookhazy** [comment]
@oc013 should I close this in favor of the discussion thread? I hadn't seen the note on documentation requests belonging there when I created this.

**Comment by oc013** [comment]
> @oc013 should I close this in favor of the discussion thread? I hadn't seen the note on documentation requests belonging there when I created this.

Probably, I'll try to keep the new discussion thread updated as we move forward.

**Comment by jdobyns** [comment]
Why did the docker-compose files get removed? 

That was the easiest way to a working setup.....

Seems like a stupid thing to remove.
